/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progratransporte;

/**
 *
 * @author claudio
 */
public class PrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUsuario
     */
    public PrincipalUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escrito = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarchofer = new javax.swing.JMenuItem();
        buscarcolegio = new javax.swing.JMenuItem();
        buscarpersonal = new javax.swing.JMenuItem();
        buscarbus = new javax.swing.JMenuItem();
        buscarpasajero = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tablamensualidad = new javax.swing.JMenuItem();
        formulariotraslado = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        agregachofer = new javax.swing.JMenuItem();
        agregacolegio = new javax.swing.JMenuItem();
        agregapersonal = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escrito.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritoLayout = new javax.swing.GroupLayout(escrito);
        escrito.setLayout(escritoLayout);
        escritoLayout.setHorizontalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritoLayout.setVerticalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/draw_dodge_burn.png"))); // NOI18N
        jMenu1.setText("Buscar");

        buscarchofer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_green.png"))); // NOI18N
        buscarchofer.setText("chofer");
        buscarchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarchoferActionPerformed(evt);
            }
        });
        jMenu1.add(buscarchofer);

        buscarcolegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reseller_account.png"))); // NOI18N
        buscarcolegio.setText("colegio");
        buscarcolegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcolegioActionPerformed(evt);
            }
        });
        jMenu1.add(buscarcolegio);

        buscarpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_silhouette.png"))); // NOI18N
        buscarpersonal.setText("personal");
        buscarpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpersonalActionPerformed(evt);
            }
        });
        jMenu1.add(buscarpersonal);

        buscarbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/metro.png"))); // NOI18N
        buscarbus.setText("bus");
        buscarbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbusActionPerformed(evt);
            }
        });
        jMenu1.add(buscarbus);

        buscarpasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_red.png"))); // NOI18N
        buscarpasajero.setText("pasajero");
        buscarpasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpasajeroActionPerformed(evt);
            }
        });
        jMenu1.add(buscarpasajero);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_multiple.png"))); // NOI18N
        jMenu2.setText("mensualidad y traslado");

        tablamensualidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        tablamensualidad.setText("tablamensualidad");
        tablamensualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablamensualidadActionPerformed(evt);
            }
        });
        jMenu2.add(tablamensualidad);

        formulariotraslado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/font_red.png"))); // NOI18N
        formulariotraslado.setText("formulariotraslado");
        formulariotraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulariotrasladoActionPerformed(evt);
            }
        });
        jMenu2.add(formulariotraslado);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        jMenu5.setText("Agregar");

        agregachofer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        agregachofer.setText("chofer");
        agregachofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregachoferActionPerformed(evt);
            }
        });
        jMenu5.add(agregachofer);

        agregacolegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        agregacolegio.setText("colegio");
        agregacolegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregacolegioActionPerformed(evt);
            }
        });
        jMenu5.add(agregacolegio);

        agregapersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        agregapersonal.setText("personal");
        agregapersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregapersonalActionPerformed(evt);
            }
        });
        jMenu5.add(agregapersonal);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarchoferActionPerformed
        // TODO add your handling code here:
        Buscarchofer bu=new  Buscarchofer();
        bu.setVisible(true);
        escrito.add(bu);
        
        
    }//GEN-LAST:event_buscarchoferActionPerformed

    private void agregachoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregachoferActionPerformed
        // TODO add your handling code here:
        Agregarchofer cho=new Agregarchofer();
        escrito.add(cho);
        cho.setVisible(true);
    }//GEN-LAST:event_agregachoferActionPerformed

    private void buscarcolegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcolegioActionPerformed
        // TODO add your handling code here:
         Buscarcolegio bu=new  Buscarcolegio();
        bu.setVisible(true);
        escrito.add(bu);
    }//GEN-LAST:event_buscarcolegioActionPerformed

    private void buscarpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpersonalActionPerformed
        // TODO add your handling code here:
         Buscarpersonal bu=new  Buscarpersonal();
        bu.setVisible(true);
        escrito.add(bu);
    }//GEN-LAST:event_buscarpersonalActionPerformed

    private void buscarbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbusActionPerformed
        // TODO add your handling code here:
         BuscarBus bu=new  BuscarBus();
        bu.setVisible(true);
        escrito.add(bu);
    }//GEN-LAST:event_buscarbusActionPerformed

    private void buscarpasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpasajeroActionPerformed
        // TODO add your handling code here:
         Buscarpasajero bu=new  Buscarpasajero();
        bu.setVisible(true);
        escrito.add(bu);
    }//GEN-LAST:event_buscarpasajeroActionPerformed

    private void tablamensualidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablamensualidadActionPerformed
        // TODO add your handling code here:
        Tablamensualidad ta = new Tablamensualidad ();
        ta.setVisible(true);
        escrito.add(ta);
    }//GEN-LAST:event_tablamensualidadActionPerformed

    private void formulariotrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulariotrasladoActionPerformed
        // TODO add your handling code here:
        formularioTraslado fr= new   formularioTraslado();
        fr.setVisible(true);
        escrito.add(fr);
    }//GEN-LAST:event_formulariotrasladoActionPerformed

    private void agregacolegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregacolegioActionPerformed
        // TODO add your handling code here:
        Agregarcolegio cho=new Agregarcolegio();
        escrito.add(cho);
        cho.setVisible(true);
    }//GEN-LAST:event_agregacolegioActionPerformed

    private void agregapersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregapersonalActionPerformed
        // TODO add your handling code here:
        Agregarpersonal cho=new Agregarpersonal();
        escrito.add(cho);
        cho.setVisible(true);
    }//GEN-LAST:event_agregapersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregachofer;
    private javax.swing.JMenuItem agregacolegio;
    private javax.swing.JMenuItem agregapersonal;
    private javax.swing.JMenuItem buscarbus;
    private javax.swing.JMenuItem buscarchofer;
    private javax.swing.JMenuItem buscarcolegio;
    private javax.swing.JMenuItem buscarpasajero;
    private javax.swing.JMenuItem buscarpersonal;
    private javax.swing.JPanel escrito;
    private javax.swing.JMenuItem formulariotraslado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem tablamensualidad;
    // End of variables declaration//GEN-END:variables
}
