/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progratransporte;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author claudio
 */
public class Tablamensualidad extends javax.swing.JInternalFrame {
    DefaultTableModel modelo=new DefaultTableModel();
conectar con;

    /**
     * Creates new form Tablamensualidad
     */
    public Tablamensualidad() {
        initComponents();
        con=new conectar();
        modelo.addColumn("personal en caja");
        
//        modelo.addColumn("Direccion");
//        modelo.addColumn("Comuna");
//        modelo.addColumn("Tipificacion");
//        modelo.addColumn("L.actual");
//        modelo.addColumn("L.Anterior");
        tablaregis.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        añadir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaregis = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jmensualidad = new javax.swing.JComboBox();
        txtconsulta = new javax.swing.JTextField();
        consulta = new javax.swing.JButton();
        txtlogin = new javax.swing.JTextField();
        txtmes = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("Login");

        jLabel4.setText("Monto");

        jLabel5.setText("Año");

        jLabel6.setText("Mes");

        Registrar.setText("Registrar");
        Registrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RegistrarItemStateChanged(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Rut");

        nuevo.setText("nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        añadir.setText("añadir a tabla");
        añadir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                añadirItemStateChanged(evt);
            }
        });
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        tablaregis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaregis);

        jLabel3.setText("mensualidad");

        jmensualidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cancelada", "pendiente" }));

        consulta.setText("consultar");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Registrar)
                                        .addGap(47, 47, 47)
                                        .addComponent(añadir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(consulta)))
                                .addGap(27, 27, 27)
                                .addComponent(nuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtlogin, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtrut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtaño, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(txtmes)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(41, 41, 41)
                                        .addComponent(jmensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jmensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar)
                    .addComponent(añadir)
                    .addComponent(nuevo))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
       
//        try{
//            PreparedStatement pstm =con.getConection().prepareStatement("select codigo,rut,login from mensualidad where login like '%"+this.jlogin.getSelectedItem()+"'%'");
//            ResultSet res=pstm.executeQuery();
//        } catch (SQLException ex) {
//        Logger.getLogger(Tablamensualidad.class.getName()).log(Level.SEVERE, null, ex);
//    }
         String bu = txtrut.getText();
        String pa= txtlogin.getText();
        String dia = txtaño.getText();    
        String hs = txtmes.getText();  
        String hll = txtmonto.getText();  
        String men=(String)jmensualidad.getSelectedItem();
        ta.registrar(bu, pa, dia, hs, hll,men);    
        
        updateTable();
        
       
    }//GEN-LAST:event_RegistrarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
         fila = tabla.rowAtPoint(evt.getPoint());                 
      if(fila>-1){
       txtrut.setText(String.valueOf(tabla.getValueAt(fila, 1)));
        txtlogin.setText(String.valueOf(tabla.getValueAt(fila, 2)));
        txtaño.setText(String.valueOf(tabla.getValueAt(fila, 3)));
        txtmes.setText(String.valueOf(tabla.getValueAt(fila, 4)));
        txtmonto.setText(String.valueOf(tabla.getValueAt(fila, 5)));
       
      }
    }//GEN-LAST:event_tablaMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        updateTable();
        nuevo();
//        mensualidad men=new mensualidad();
//        try{
//        PreparedStatement pstm=con.getConection().prepareStatement("select login,mes from mensualidad ");
//        ResultSet res=pstm.executeQuery();
//        while(res.next()){
//            this.jlogin.addItem(res.getString("login"));
//            this.jmes.addItem(res.getString("mes"));
//        }
//        } catch (SQLException ex) {
//    
        
    }//GEN-LAST:event_formInternalFrameOpened
// void mostrardatos(String valor){
//    
//    modelo.addColumn("rut");
//    modelo.addColumn("mes");
//    modelo.addColumn("mensualidad");
//    tablaregis.setModel(modelo);
//   String sql="";
//    if(valor.equals(""))
//    {
//        sql="SELECT * FROM mensualidad";
//    }
// 
//    String []datos = new String [3];
//        try {
//            PreparedStatement pstm=con.getConection().prepareStatement("select rut,mes,mensualidad from mensualidad");
//            ResultSet rs = pstm.executeQuery();
//            while(rs.next()){
//                datos[0]=rs.getString(1);
//                datos[1]=rs.getString(2);
//                datos[2]=rs.getString(3);
//                modelo.addRow(datos);
//            }
//            tablaregis.setModel(modelo);
//        } catch (SQLException ex) {
//            Logger.getLogger(Tablamensualidad.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this.setTitle(" tabla mensualidad");
    }//GEN-LAST:event_formInternalFrameActivated

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
         
         String []datos=new String[1];
            datos[0]=txtlogin.getText();
//        datos[1]=(String)jlogin.getSelectedItem();
//        datos[2] = txtaño.getText();
//        datos[3]= (String)jmes.getSelectedItem();   
//        datos[4]=txtmonto.getText();
            modelo.addRow(datos);
        
         
    }//GEN-LAST:event_añadirActionPerformed

    private void RegistrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RegistrarItemStateChanged
        
             
        
    }//GEN-LAST:event_RegistrarItemStateChanged

    private void añadirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_añadirItemStateChanged
        // TODO add your handling code here:
        
           
    }//GEN-LAST:event_añadirItemStateChanged

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
      
        try {
        
            String codBuscar =txtconsulta.getText();
           PreparedStatement pstm=con.getConection().prepareStatement("SELECT mensualidad  FROM mensualidad ");
        ResultSet  res = pstm.executeQuery();
            boolean encontro = false;
            while (res.next()) {
                if (codBuscar.equals(res.getObject("mensualidad"))) {
                    encontro = true;
                    break;
                }
            }
            String SQL = "SELECT * FROM mensualidad where mensualidad='" + codBuscar + "'";
//            modelo = con.retornarDatosTabla(SQL);
//            tablaregis.setModel(modelo);
//            jScrollPane2.getViewport().add(tablaregis);
//            if (encontro == false) {
//                JOptionPane.showMessageDialog(null, "no existe Estudiante Buscado");
//            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consultaActionPerformed
mensualidad ta=new mensualidad();
 Object[][] per; 
    int fila = -1;
    public void nuevo(){
        txtrut.setText("");
        txtaño.setText("");
       
        txtmonto.setText("");
        
    }
    public void updateTable(){
        String [] colum={"codigo","rut","login", "año", "mes", "monto","mensualidad"};
        per = ta.getDatos();
               
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(per,colum);                        
        tabla.setModel(datos); 
        //ajustamos tamaño de la celda ID
        TableColumn columna = tabla.getColumn("codigo");        
        columna.setPreferredWidth(50);
        columna.setMinWidth(10);
        columna.setMaxWidth(30);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton añadir;
    private javax.swing.JButton consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jmensualidad;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaregis;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtconsulta;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
